"""add_scheduled_definitions_and_entries

Revision ID: 6a5525e8960a
Revises: a2b3c4d5e6f7
Create Date: 2026-04-11 08:28:20.041242
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '6a5525e8960a'
down_revision: Union[str, None] = 'a2b3c4d5e6f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scheduled_definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('frequency', sa.String(length=20), nullable=False),
    sa.Column('payment_day', sa.Integer(), nullable=False),
    sa.Column('start_month', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_scheddef_active', 'scheduled_definitions', ['is_active'], unique=False)
    op.create_index('ix_scheddef_type', 'scheduled_definitions', ['source_type'], unique=False)
    op.create_table('scheduled_entries',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('definition_id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(length=30), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_paid', sa.Boolean(), nullable=False),
    sa.Column('paid_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['definition_id'], ['scheduled_definitions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_schedentry_date', 'scheduled_entries', ['entry_date'], unique=False)
    op.create_index('ix_schedentry_paid', 'scheduled_entries', ['is_paid'], unique=False)
    op.create_index('ix_schedentry_source', 'scheduled_entries', ['source_type', 'definition_id'], unique=False)
    op.drop_table('check_uploads')
    op.drop_index('ix_checks_bank_tx', table_name='checks')
    op.drop_index('ix_checks_due_date', table_name='checks')
    op.drop_index('ix_checks_vendor_code', table_name='checks')
    op.drop_table('checks')
    op.drop_index('ix_bank_stmt_account', table_name='bank_statements')
    op.drop_index('ix_bank_tx_account_date_desc', table_name='bank_transactions')
    op.drop_index('ix_bank_tx_category', table_name='bank_transactions')
    op.drop_index('ix_bank_tx_match', table_name='bank_transactions')
    op.drop_index('ix_bank_tx_payment_method', table_name='bank_transactions')
    op.drop_index('ix_bank_tx_vendor', table_name='bank_transactions')
    op.alter_column('credit_payments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('credit_products', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('credit_products', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_exchange_rates_currency_date', table_name='exchange_rates')
    op.drop_index('idx_fe_date_id', table_name='finance_events')
    op.create_index(op.f('ix_finance_events_event_date'), 'finance_events', ['event_date'], unique=False)
    op.drop_index('ix_messages_conv_created', table_name='messages')
    op.alter_column('quality_forms', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('quality_forms', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('quality_templates', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('quality_templates', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('transaction_categories', 'sort_order',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('transaction_categories', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('transaction_categories', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('vendor_transactions', 'borc',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=False,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('vendor_transactions', 'alacak',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=False,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('vendor_transactions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_vendor_tx_match', table_name='vendor_transactions')
    op.drop_index('ix_vtx_department', table_name='vendor_transactions')
    op.drop_index('ix_vtx_dept_status', table_name='vendor_transactions')
    op.alter_column('vendor_uploads', 'total_vendors',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('vendor_uploads', 'total_transactions',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('vendor_uploads', 'new_transactions',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('vendor_uploads', 'skipped_transactions',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('vendor_uploads', 'uploaded_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('vendors', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vendors', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('vendor_uploads', 'uploaded_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('vendor_uploads', 'skipped_transactions',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('vendor_uploads', 'new_transactions',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('vendor_uploads', 'total_transactions',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('vendor_uploads', 'total_vendors',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.create_index('ix_vtx_dept_status', 'vendor_transactions', ['dept_status'], unique=False)
    op.create_index('ix_vtx_department', 'vendor_transactions', ['department_id'], unique=False)
    op.create_index('ix_vendor_tx_match', 'vendor_transactions', ['match_number'], unique=False)
    op.alter_column('vendor_transactions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('vendor_transactions', 'alacak',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=True,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('vendor_transactions', 'borc',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=True,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('transaction_categories', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('transaction_categories', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('transaction_categories', 'sort_order',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('quality_templates', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('quality_templates', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('quality_forms', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('quality_forms', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index('ix_messages_conv_created', 'messages', ['conversation_id', 'created_at'], unique=False)
    op.drop_index(op.f('ix_finance_events_event_date'), table_name='finance_events')
    op.create_index('idx_fe_date_id', 'finance_events', [sa.text('event_date DESC'), sa.text('id DESC')], unique=False)
    op.create_index('ix_exchange_rates_currency_date', 'exchange_rates', ['currency_code', sa.text('date DESC')], unique=False)
    op.alter_column('credit_products', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('credit_products', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('credit_payments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index('ix_bank_tx_vendor', 'bank_transactions', ['vendor_id'], unique=False)
    op.create_index('ix_bank_tx_payment_method', 'bank_transactions', ['payment_method'], unique=False)
    op.create_index('ix_bank_tx_match', 'bank_transactions', ['match_number'], unique=False)
    op.create_index('ix_bank_tx_category', 'bank_transactions', ['category_id'], unique=False)
    op.create_index('ix_bank_tx_account_date_desc', 'bank_transactions', ['account_id', sa.text('date DESC'), sa.text('id DESC')], unique=False)
    op.create_index('ix_bank_stmt_account', 'bank_statements', ['account_id'], unique=False)
    op.create_table('checks',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('upload_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('check_type', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('sequence_no', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('check_no', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('vendor_code', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('vendor_name', sa.VARCHAR(length=300), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('city', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('due_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('amount_tl', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False),
    sa.Column('currency', sa.VARCHAR(length=5), server_default=sa.text("'TL'::character varying"), autoincrement=False, nullable=True),
    sa.Column('amount_currency', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False),
    sa.Column('transaction_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('bank_transaction_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('match_number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('matched_vendor_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['bank_transaction_id'], ['bank_transactions.id'], name='checks_bank_transaction_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['matched_vendor_id'], ['vendors.id'], name='checks_matched_vendor_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['upload_id'], ['check_uploads.id'], name='checks_upload_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='checks_pkey'),
    sa.UniqueConstraint('check_no', 'vendor_code', 'due_date', name='uq_check_no_vendor_date')
    )
    op.create_index('ix_checks_vendor_code', 'checks', ['vendor_code'], unique=False)
    op.create_index('ix_checks_due_date', 'checks', ['due_date'], unique=False)
    op.create_index('ix_checks_bank_tx', 'checks', ['bank_transaction_id'], unique=False)
    op.create_table('check_uploads',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('file_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('file_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('total_checks', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('new_checks', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('skipped_checks', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('uploaded_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('uploaded_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], name='check_uploads_uploaded_by_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='check_uploads_pkey')
    )
    op.drop_index('ix_schedentry_source', table_name='scheduled_entries')
    op.drop_index('ix_schedentry_paid', table_name='scheduled_entries')
    op.drop_index('ix_schedentry_date', table_name='scheduled_entries')
    op.drop_table('scheduled_entries')
    op.drop_index('ix_scheddef_type', table_name='scheduled_definitions')
    op.drop_index('ix_scheddef_active', table_name='scheduled_definitions')
    op.drop_table('scheduled_definitions')
    # ### end Alembic commands ###
