"""add_agency_groups_table

Revision ID: 7d052738619a
Revises: p4q5r6s7t8u9
Create Date: 2026-05-23
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = '7d052738619a'
down_revision: Union[str, None] = 'e9f3b7d2c5a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        'agency_groups',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('members', sa.JSON(), nullable=False, server_default='[]'),
        sa.Column('created_at', sa.DateTime(timezone=True),
                  server_default=sa.text("now()"), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True),
                  server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name', name='uq_agency_groups_name'),
    )
    op.create_index('ix_agency_groups_id', 'agency_groups', ['id'])

    # Mevcut grupları seed et
    op.execute("""
        INSERT INTO agency_groups (name, members) VALUES
        ('ALLTOURS',  '["ALLTOURS D", "ALLTOURS NV"]'),
        ('ANEX',      '["ANEX EU", "ANEX BDT", "ANEXPOL", "ANEXTORO"]'),
        ('BYEBYE',    '["BYEBYE D", "BYEBYE NV"]'),
        ('CORAL',     '["CORAL RU", "CORAL PL", "CORAL CZ", "CORALTR", "CORAL DEU"]'),
        ('WEBRES',    '["WEBRES", "WEBRES EU"]'),
        ('MUNFERIT',  '["MUNFERIT TL", "MUNFERIT EUR", "MUNFERIT USD"]'),
        ('LIBERO',    '["LIBERO TOUR", "LIBERO DEU"]')
    """)


def downgrade() -> None:
    # placeholder — rest of old autogenerate content removed
    pass


def _old_upgrade_do_not_run() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_checks_bank_tx', table_name='checks')
    op.drop_index('ix_checks_due_date', table_name='checks')
    op.drop_index('ix_checks_vendor_code', table_name='checks')
    op.drop_table('checks')
    op.drop_table('check_uploads')
    op.create_index(op.f('ix_approval_request_logs_id'), 'approval_request_logs', ['id'], unique=False)
    op.create_index(op.f('ix_approval_requests_id'), 'approval_requests', ['id'], unique=False)
    op.create_index(op.f('ix_approval_workflow_approver_roles_id'), 'approval_workflow_approver_roles', ['id'], unique=False)
    op.create_index(op.f('ix_approval_workflow_requestor_roles_id'), 'approval_workflow_requestor_roles', ['id'], unique=False)
    op.create_index(op.f('ix_approval_workflow_steps_id'), 'approval_workflow_steps', ['id'], unique=False)
    op.create_index(op.f('ix_approval_workflows_id'), 'approval_workflows', ['id'], unique=False)
    op.create_unique_constraint(None, 'approval_workflows', ['name'])
    op.drop_index('ix_bank_stmt_account', table_name='bank_statements')
    op.drop_index('ix_bank_tx_account_date_desc', table_name='bank_transactions')
    op.drop_index('ix_bank_tx_match', table_name='bank_transactions')
    op.drop_index('ix_bank_tx_payment_method', table_name='bank_transactions')
    op.drop_index('ix_bank_tx_vendor', table_name='bank_transactions')
    op.alter_column('credit_payments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('credit_products', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('credit_products', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_credit_products_linked_account', table_name='credit_products')
    op.drop_index('ix_exchange_rates_currency_date', table_name='exchange_rates')
    op.drop_index('idx_fe_date_id', table_name='finance_events')
    op.create_index(op.f('ix_finance_events_event_date'), 'finance_events', ['event_date'], unique=False)
    op.drop_index('ix_messages_conv_created', table_name='messages')
    op.alter_column('quality_forms', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('quality_forms', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('quality_templates', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('quality_templates', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('scheduled_definitions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('scheduled_definitions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('scheduled_entries', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('scheduled_entries', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('transaction_categories', 'sort_order',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('transaction_categories', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('transaction_categories', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('vendor_transactions', 'borc',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=False,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('vendor_transactions', 'alacak',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=False,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('vendor_transactions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_vendor_tx_match', table_name='vendor_transactions')
    op.drop_index('ix_vtx_department', table_name='vendor_transactions')
    op.drop_index('ix_vtx_dept_status', table_name='vendor_transactions')
    op.alter_column('vendor_uploads', 'total_vendors',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('vendor_uploads', 'total_transactions',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('vendor_uploads', 'new_transactions',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('vendor_uploads', 'skipped_transactions',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('vendor_uploads', 'uploaded_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('vendors', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vendors', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('vendor_uploads', 'uploaded_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('vendor_uploads', 'skipped_transactions',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('vendor_uploads', 'new_transactions',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('vendor_uploads', 'total_transactions',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('vendor_uploads', 'total_vendors',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.create_index('ix_vtx_dept_status', 'vendor_transactions', ['dept_status'], unique=False)
    op.create_index('ix_vtx_department', 'vendor_transactions', ['department_id'], unique=False)
    op.create_index('ix_vendor_tx_match', 'vendor_transactions', ['match_number'], unique=False)
    op.alter_column('vendor_transactions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('vendor_transactions', 'alacak',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=True,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('vendor_transactions', 'borc',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=True,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('transaction_categories', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('transaction_categories', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('transaction_categories', 'sort_order',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('scheduled_entries', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('scheduled_entries', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('scheduled_definitions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('scheduled_definitions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('quality_templates', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('quality_templates', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('quality_forms', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('quality_forms', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index('ix_messages_conv_created', 'messages', ['conversation_id', 'created_at'], unique=False)
    op.drop_index(op.f('ix_finance_events_event_date'), table_name='finance_events')
    op.create_index('idx_fe_date_id', 'finance_events', [sa.text('event_date DESC'), sa.text('id DESC')], unique=False)
    op.create_index('ix_exchange_rates_currency_date', 'exchange_rates', ['currency_code', sa.text('date DESC')], unique=False)
    op.create_index('ix_credit_products_linked_account', 'credit_products', ['linked_account_id'], unique=False)
    op.alter_column('credit_products', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('credit_products', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('credit_payments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index('ix_bank_tx_vendor', 'bank_transactions', ['vendor_id'], unique=False)
    op.create_index('ix_bank_tx_payment_method', 'bank_transactions', ['payment_method'], unique=False)
    op.create_index('ix_bank_tx_match', 'bank_transactions', ['match_number'], unique=False)
    op.create_index('ix_bank_tx_account_date_desc', 'bank_transactions', ['account_id', sa.text('date DESC'), sa.text('id DESC')], unique=False)
    op.create_index('ix_bank_stmt_account', 'bank_statements', ['account_id'], unique=False)
    op.drop_constraint(None, 'approval_workflows', type_='unique')
    op.drop_index(op.f('ix_approval_workflows_id'), table_name='approval_workflows')
    op.drop_index(op.f('ix_approval_workflow_steps_id'), table_name='approval_workflow_steps')
    op.drop_index(op.f('ix_approval_workflow_requestor_roles_id'), table_name='approval_workflow_requestor_roles')
    op.drop_index(op.f('ix_approval_workflow_approver_roles_id'), table_name='approval_workflow_approver_roles')
    op.drop_index(op.f('ix_approval_requests_id'), table_name='approval_requests')
    op.drop_index(op.f('ix_approval_request_logs_id'), table_name='approval_request_logs')
    op.create_table('check_uploads',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('check_uploads_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('file_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('file_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('total_checks', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('new_checks', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('skipped_checks', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('uploaded_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('uploaded_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], name='check_uploads_uploaded_by_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='check_uploads_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('checks',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('upload_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('check_type', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('sequence_no', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('check_no', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('vendor_code', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('vendor_name', sa.VARCHAR(length=300), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('city', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('due_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('amount_tl', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False),
    sa.Column('currency', sa.VARCHAR(length=5), server_default=sa.text("'TL'::character varying"), autoincrement=False, nullable=True),
    sa.Column('amount_currency', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False),
    sa.Column('transaction_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('bank_transaction_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('match_number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('matched_vendor_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['bank_transaction_id'], ['bank_transactions.id'], name='checks_bank_transaction_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['matched_vendor_id'], ['vendors.id'], name='checks_matched_vendor_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['upload_id'], ['check_uploads.id'], name='checks_upload_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='checks_pkey'),
    sa.UniqueConstraint('check_no', 'vendor_code', 'due_date', name='uq_check_no_vendor_date')
    )
    op.create_index('ix_checks_vendor_code', 'checks', ['vendor_code'], unique=False)
    op.create_index('ix_checks_due_date', 'checks', ['due_date'], unique=False)
    op.create_index('ix_checks_bank_tx', 'checks', ['bank_transaction_id'], unique=False)
    # ### end Alembic commands ###
