"""add_composite_index_messages

Revision ID: df2165d9264c
Revises: f1a2b3c4d5e6
Create Date: 2026-02-25 03:17:19.185305
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'df2165d9264c'
down_revision: Union[str, None] = 'f1a2b3c4d5e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('modules', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('modules_code_key', 'modules', type_='unique')
    op.drop_index('ix_modules_code', table_name='modules')
    op.create_index(op.f('ix_modules_code'), 'modules', ['code'], unique=True)
    op.alter_column('role_module_permissions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('roles', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))

    # Mesaj sorgulama performansı için composite index (IF NOT EXISTS)
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_messages_conv_created "
        "ON messages (conversation_id, created_at)"
    )
    # NOT: ix_messages_conv_deleted_created f1a2b3c4d5e6 migration'ında oluşturulur ve orada
    # düşürülür. Buradaki tekrar (IF NOT EXISTS) no-op olduğu için kaldırıldı; aksi halde
    # downgrade'de çift drop (UndefinedObject) hatası oluyordu.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # ix_messages_conv_deleted_created f1a2b3c4d5e6 tarafından yönetilir; burada düşürülmez
    op.drop_index('ix_messages_conv_created', table_name='messages')

    op.alter_column('roles', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('role_module_permissions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_modules_code'), table_name='modules')
    op.create_index('ix_modules_code', 'modules', ['code'], unique=False)
    op.create_unique_constraint('modules_code_key', 'modules', ['code'])
    op.alter_column('modules', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###
